### ISSUE TITLE
Conselhos 

### ISSUE THREAD

**Issue by farribeiro** [flathub/br.gov.fazenda.receita.irpf#57]
Preciso de seus conselhos a respeito deste código... Onde estou errando?

```yaml
id: br.jus.pjeofficepro
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk17
tags:
  - proprietary
command: pjeoffice-pro

finish-args:
  - --share=network
  - --socket=x11
  - --socket=cups
  - --socket=pcsc
  - --share=ipc
  - --device=all
  - --env=PATH=/app/jre/bin:/app/bin:/usr/bin
  - --env=JAVA_HOME=/app/jre
  - --filesystem=xdg-documents # Useful place to save PDF files.

add-extensions:
  org.freedesktop.Platform.ffmpeg-full:
    directory: lib/ffmpeg
    add-ld-path: .
    version: '23.08'
    no-autodownload: true
    autodelete: false

modules:
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk17/install.sh

  - name: pjeofficepro
    buildsystem: simple
    build-commands:
      - install -Dm755 -t /app/bin apply_extra
      - install -Dm755 -t /app/bin pjeoffice-pro
    sources:
      - type: script
        dest-filename: apply_extra
        commands:
          - set -e
          - export LC_ALL=C
          - mkdir share
          - |
            bsdtar -C share -xf pje.zip --strip-components 1 \
              --include='pjeoffice-pro/cutplayer4jfx.jar' \
              --include='pjeoffice-pro/pjeoffice-pro.jar' \
              --include='pjeoffice-pro/pjeoffice-pro.sh' \
              --include='pjeoffice-pro/LEIA-ME.TXT' \
              --include='pjeoffice-pro/ffmpeg.exe' \
              --include='pjeoffice-pro/pjeoffice-update.properties'
          - rm -f pje.zip
      - type: extra-data
        filename: pje.zip
        url: https://pje-office.pje.jus.br/pro/pjeoffice-pro-v2.5.13u-linux_x64.zip
        size: 167503756
        sha256: b0b342304c2c7a4000111a94c96bc0d3a7ab6bad0f85ae07af4bbe29ec82188a
      - type: script
        dest-filename: pjeoffice-pro
        commands:
          - |
            debugMode=false

            currentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
            currentDIR=$currentDIR | sed -e 's/ /\\ /g'
            cd "$currentDIR"
            chmod 755 ffmpeg.exe
            chmod 755 ./jre/bin/java
            a3auto=true
            if [ "$debugMode" = false ]; then
              rm -rf ~/.pjeoffice-pro/*.log*
            else
                a3auto=false
                rm -rf ~/.pjeoffice-pro
            fi

            nohup java \
            -XX:+UseG1GC \
            -XX:MinHeapFreeRatio=3 \
            -XX:MaxHeapFreeRatio=3 \
            -Xms20m \
            -Xmx2048m \
            -Dpjeoffice_home="$currentDIR" \
            -Dffmpeg_home="$currentDIR" \
            -Dpjeoffice_looksandfeels="Metal" \
            -Dcutplayer4j_looksandfeels="Nimbus" \
            -Dsigner4j_a3auto="$a3auto" \
            -jar \
            pjeoffice-pro.jar >/dev/null 2>&1 &

            # Aguarda 1 segundo antes de finalizar a seção atual
            sleep 1

            # Fecha a tela preta do script
            exit
```
